name: Browser Agent QA Testing

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository to scan (owner/repo format)'
        required: false
        type: string
        default: 'Caleb-Hurst/First-Workflow'

jobs:
  browser-testing:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          npm init -y
          npm install @octokit/rest openai dotenv

      - name: Setup Browser Agent Dependencies
        run: |
          if ! command -v uv &> /dev/null; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          export PATH="$HOME/.local/bin:$PATH"
          uv sync
          uv run playwright install chromium --with-deps

      - name: Process Issues with Browser Testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HEADLESS: "true"
          TIMEOUT: "300"
          TARGET_REPO: ${{ github.event.inputs.target_repo || 'Caleb-Hurst/bernard_browser_agent' }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          echo "🎯 Target Repository: $TARGET_REPO"
          echo "🔍 Scanning for ALL issues with 'needs-test' label..."
          node integrations/enhanced_workflow.js

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: browser-test-results
          path: |
            logs/
            screenshots/
            *.log
          retention-days: 7
